version: '3.3'
services:
  cuda:
    container_name: cuda
    image: nvidia/cuda-local
    command: tail -f /dev/null
    working_dir: /workspace
    volumes:
      - ./:/workspace
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
